project:
  type: website
  output-dir: docs
website:
  title: "Xtophe Bontemps"
  navbar:
    pinned: true
    background: light
    left:
      - href: academics.qmd
        text: Academics
      - href: dataviz.qmd
        text: Data Visualization
      - href: training.qmd
        text: Training
    right:
      - icon: github
        href: https://github.com/XtopheB
      - icon: linkedin
        href: https://linkedin.com/in/cbontemps/

format:
  html:
    theme: litera
    css: Mystyle.css
    toc: false
  



